name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build Angular app for production
      - name: Build Angular app
        run: |
          # Build ignoring budgets to prevent failure
          ng build --configuration=production --base-href /ResumeBuilder7777/ --stats-json

      # Step 5: Detect actual dist folder
      - name: Detect dist folder
        id: dist
        run: |
          APP_DIST=$(ls dist)
          echo "DIST_FOLDER=$APP_DIST" >> $GITHUB_ENV

      # Step 6: List dist folder for debugging
      - name: List dist folder
        run: ls dist/$DIST_FOLDER

      # Step 7: Create 404 fallback for routing
      - name:
